Chess.CMS/Areas/Admin/Controllers/HomeAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Chess.CMS.Areas.Admin.Controllers
{
    public class HomeAdminController : Controller
    {
        // GET: Admin/HomeAdmin
        public ActionResult Index()
        {
            return View();
        }
    }
}

Chess.CMS/Areas/Admin/Controllers/PlayersController.cs
using Chess.CMS.Repository;
using Chess.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Chess.CMS.Areas.Admin.Controllers
{
    public class PlayersController : Controller
    {
        private GenericUnitOfWork _unitOfWork = new GenericUnitOfWork();
        // GET: Admin/Players
        public ActionResult Index()
        {
            var lstPlayer = _unitOfWork.GetRepositoryInstance<Player>().GetAllRecords().OrderBy(o => o.ID).ToList();
            return View(lstPlayer);
        }
        public ActionResult AddPlayer()
        {
            return View();
        }
        public ActionResult EditPlayer(long id)
        {
            Player module = new Player();
            module = _unitOfWork.GetRepositoryInstance<Player>().GetFirstOrDefaultByParameter(o => o.ID == id);
            if (module != null)
            {
                return View(module);
            }
            else
            {
                TempData["error"] = "bản ghi không tồn tại";
                return Json("bản ghi không tồn tại", JsonRequestBehavior.AllowGet);
            }
        }
        public async Task<JsonResult> AddToPlayer(string name, string birthday, string country, string elo,string score, string note)
        {
            try
            {
                Player item = new Player();
                item.name = name;
                item.birthday = DateTime.Parse(birthday);
                item.country = country;
                item.elo = int.Parse(elo);
                item.score = int.Parse(score);
                item.note = note;
                _unitOfWork.GetRepositoryInstance<Player>().Add(item);
                _unitOfWork.SaveChanges();

                TempData["message"] = "Thêm  mới thành công!";
                return Json("OK", JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                TempData["error"] = "Lỗi thêm mới: " + ex.Message;
                return Json("Lỗi thêm mới", JsonRequestBehavior.AllowGet);
            }
        }
        public async Task<JsonResult> EditToPlayer(long id, string name, string birthday, string country, string elo,string score, string note)
        {
            try
            {
                Player item = new Player();
                item = _unitOfWork.GetRepositoryInstance<Player>().GetFirstOrDefaultByParameter(o => o.ID == id);
                if (item != null)
                {
                    item.name = name;
                    item.birthday = DateTime.Parse(birthday);
                    item.country = country;
                    item.elo = int.Parse(elo);
                    item.score = int.Parse(score);
                    item.note = note;
                    _unitOfWork.GetRepositoryInstance<Player>().Update(item);
                    _unitOfWork.SaveChanges();
                }
                else
                {
                    TempData["error"] = "bản ghi không tồn tại";
                    return Json("bản ghi không tồn tại", JsonRequestBehavior.AllowGet);
                }

                TempData["message"] = "Cập nhật thành công!";
                return Json("OK", JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                TempData["error"] = "Lỗi Cập nhật: " + ex.Message;
                return Json("Lỗi Cập nhật", JsonRequestBehavior.AllowGet);
            }
        }
        public async Task<JsonResult> Xoa(long id)
        {
            try
            {
                Player item = new Player();
                item = _unitOfWork.GetRepositoryInstance<Player>().GetFirstOrDefaultByParameter(o => o.ID == id);
                if (item != null)
                {
                    _unitOfWork.GetRepositoryInstance<Player>().Remove(item);
                    _unitOfWork.SaveChanges();
                }
                else
                {
                    TempData["error"] = "bản ghi không tồn tại";
                    return Json("bản ghi không tồn tại", JsonRequestBehavior.AllowGet);
                }

                TempData["message"] = "Xóa thành công!";
                return Json("OK", JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                TempData["error"] = "Lỗi xóa: " + ex.Message;
                return Json("Lỗi xóa", JsonRequestBehavior.AllowGet);
            }
        }
    }
}

Chess.CMS/Areas/Admin/Views/Players/AddPlayer.cshtml
@{
    ViewBag.Title = "Thêm mới Cờ thủ";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Thêm mới cờ thủ</h2>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <form class="form-horizontal form-label-left" novalidate>
                    @*<div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="mamodule">
                Mã Module <span class="required">*</span>
            </label>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <input type="text" id="mamodule" name="mamodule" required="required" class="form-control col-md-7 col-xs-12">
            </div>
        </div>*@
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="tenmodule">
                            Tên cờ thủ <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input type="text" id="name" name="name" required="required" class="form-control col-md-7 col-xs-12">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="machuongtrinh">
                            Năm sinh <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input type="date" id="birthday" name="birthday" required="required" class="form-control col-md-7 col-xs-12">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="mamon">
                            Quốc tịch <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input type="text" id="country" name="country" required="required" class="form-control col-md-7 col-xs-12">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="madot">
                            Hệ số Elo <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input type="text" id="elo" name="elo" required="required" class="form-control col-md-7 col-xs-12">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="madot">
                            Điểm số <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input type="text" id="score" name="score" required="required" class="form-control col-md-7 col-xs-12">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="thoiluong">
                            Ghi chú <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input type="text" id="note" name="note" required="required" class="form-control col-md-7 col-xs-12">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-6 col-md-offset-3">
                            @*<button type="submit" class="btn btn-primary">Cancel</button>*@
                            @Html.ActionLink("Quay lại", "Index", null, new { @class = "btn btn-primary" })

                            <button id="addPlayer" type="submit" class="btn btn-success">Thêm mới</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        $('#addPlayer').click(function () {
            var name = $('#name').val();
            var birthday = $('#birthday').val();
            var country = $('#country').val();
            var elo = $('#elo').val();
            var score = $('#score').val();
            if (name == "") {
                toastr.error('Tên Không được để trống');
                return false;
            }
            if (birthday == "") {
                toastr.error('Ngày sinh không được để trống');
                return false;
            }
            if (country == "") {
                toastr.error('Quốc gia Không được để trống');
                return false;
            }
            if (elo == "") {
                toastr.error('Elo Không được để trống');
                return false;
            }
            if (score == "") {
                toastr.error('Điểm Không được để trống');
                return false;
            }
            $.ajax({
            type: "GET",
                url: '@Url.Action("AddToPlayer", "Players")',
                data: { name: name, birthday: birthday, country: country, elo: elo, score: score, note: note },
            dataType: "json",
            contentType: 'application/json',
            success: function (data) {
                $("#divProcessing").hide();
                if (data == 'OK') {
                    window.location.href = '@Url.Action("Index", "Players")';
                    //setTimeout(function () { location.reload(); }, 2000);
                } else {
                    toastr.error(data);
                }
            },
            error: function (req, status, error) {
                $("#divProcessing").hide();
            }
        });
        });
    });
</script>
@*<script>
    $(document).ready(function () {
        LoadListChuongTrinh();
        LoadListMonHoc();
    });
    function LoadListChuongTrinh() {
        $.ajax({
            type: "GET",
            url: '@Url.Action("LoadMaChuongTrinh", "HomeAdmin")',
            dataType: "json",
            contentType: 'application/json',
            success: function (result) {
                $('#machuongtrinh').html(result);
            },
            error: function (req, status, error) {
                // do something with error
            }
        });
    }
    function LoadListMonHoc() {
        $.ajax({
            type: "GET",
            url: '@Url.Action("LoadMaMonHoc", "HomeAdmin")',
            dataType: "json",
            contentType: 'application/json',
            success: function (result) {
                $('#mamon').html(result);
            },
            error: function (req, status, error) {
                // do something with error
            }
        });
    }
</script>*@

Chess.CMS/Areas/Admin/Views/Players/EditPlayer.cshtml
@model Chess.Model.Player
@{
    ViewBag.Title = "Thêm mới Cờ thủ";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Thêm mới cờ thủ</h2>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <div class="form-horizontal form-label-left" novalidate>
                    @*<div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="mamodule">
                Mã Module <span class="required">*</span>
            </label>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <input type="text" id="mamodule" name="mamodule" required="required" class="form-control col-md-7 col-xs-12">
            </div>
        </div>*@
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="tenmodule">
                            Tên cờ thủ <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input type="hidden" name="IdEdit" id="IdEdit" value="@Model.ID" />
                            <input value="@Model.name" type="text" id="nameplayer" name="nameplayer" required="required" class="form-control col-md-7 col-xs-12">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="machuongtrinh">
                            Năm sinh <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input value="@Model.birthday" type="date" id="birthday" name="birthday" required="required" class="form-control col-md-7 col-xs-12">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="mamon">
                            Quốc tịch <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input value="@Model.country" type="text" id="country" name="country" required="required" class="form-control col-md-7 col-xs-12">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="madot">
                            Hệ số Elo <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input value="@Model.elo" type="text" id="elo" name="elo" required="required" class="form-control col-md-7 col-xs-12">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="madot">
                            Hệ số Elo <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input value="@Model.score" type="text" id="score" name="score" required="required" class="form-control col-md-7 col-xs-12">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="thoiluong">
                            Ghi chú <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input value="@Model.note" type="text" id="note" name="note" required="required" class="form-control col-md-7 col-xs-12">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-6 col-md-offset-3">
                            @*<button type="submit" class="btn btn-primary">Cancel</button>*@
                            @Html.ActionLink("Quay lại", "Index", null, new { @class = "btn btn-primary" })

                            <button id="EditPlayer" type="submit" class="btn btn-success">Sửa</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        $('#EditPlayer').click(function () {
            var ID = $('#IdEdit').val();
            var name = $('#nameplayer').val();
            var birthday = $('#birthday').val();
            var country = $('#country').val();
            var elo = $('#elo').val();
            var score = $('#score').val();
            if (name == "") {
                toastr.error('Tên Không được để trống');
                return false;
            }
            if (birthday == "") {
                toastr.error('Ngày sinh không được để trống');
                return false;
            }
            if (country == "") {
                toastr.error('Quốc gia Không được để trống');
                return false;
            }
            if (elo == "") {
                toastr.error('elo Không được để trống');
                return false;
            }
            if (score == "") {
                toastr.error('Điểm Không được để trống');
                return false;
            }
            $.ajax({
            type: "GET",
                url: '@Url.Action("EditToPlayer", "Players")',
                data: { ID: ID, name: name, birthday: birthday, country: country, elo: elo, score: score, note: note },
            dataType: "json",
            contentType: 'application/json',
            success: function (data) {
                $("#divProcessing").hide();
                if (data == 'OK') {
                    window.location.href = '@Url.Action("Index", "Players")';
                    //setTimeout(function () { location.reload(); }, 2000);
                } else {
                    toastr.error(data);
                }
            },
            error: function (req, status, error) {
                $("#divProcessing").hide();
            }
        });
        });
    });
</script>
    @*<script>
        $(document).ready(function () {
            LoadListChuongTrinh();
            LoadListMonHoc();
        });
        function LoadListChuongTrinh() {
            $.ajax({
                type: "GET",
                url: '@Url.Action("LoadMaChuongTrinh", "HomeAdmin")',
                dataType: "json",
                contentType: 'application/json',
                success: function (result) {
                    $('#machuongtrinh').html(result);
                },
                error: function (req, status, error) {
                    // do something with error
                }
            });
        }
        function LoadListMonHoc() {
            $.ajax({
                type: "GET",
                url: '@Url.Action("LoadMaMonHoc", "HomeAdmin")',
                dataType: "json",
                contentType: 'application/json',
                success: function (result) {
                    $('#mamon').html(result);
                },
                error: function (req, status, error) {
                    // do something with error
                }
            });
        }
    </script>*@