Chess.CMS/Areas/Admin/Controllers/RoundController.cs
using Chess.CMS.Repository;
using Chess.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Chess.CMS.Areas.Admin.Controllers
{
    public class RoundController : Controller
    {
        // GET: Admin/Round
        private GenericUnitOfWork _unitOfWork = new GenericUnitOfWork();

        // GET: Admin/CapHoc
        public ActionResult Index()
        {
            var lstRound = _unitOfWork.GetRepositoryInstance<Round>().GetAllRecords().OrderBy(o => o.ID).ToList();
            return View(lstRound);
        }

        public async Task<JsonResult> AddRound(string name, string note)
        {
            try
            {
                Round item = new Round();
                item.name = name.Trim();
                item.note = note.Trim();
                _unitOfWork.GetRepositoryInstance<Round>().Add(item);
                _unitOfWork.SaveChanges();

                TempData["message"] = "Thêm  mới thành công!";
                return Json("OK", JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                TempData["error"] = "Lỗi thêm mới: " + ex.Message;
                return Json("Lỗi thêm mới", JsonRequestBehavior.AllowGet);
            }
        }
        public async Task<JsonResult> EditRound(long id, string name, string note)
        {
            try
            {
                Round item = new Round();
                item = _unitOfWork.GetRepositoryInstance<Round>().GetFirstOrDefaultByParameter(o => o.ID == id);
                if (item != null)
                {
                    item.name = name.Trim();
                    item.note = note.Trim();
                    _unitOfWork.GetRepositoryInstance<Round>().Update(item);
                    _unitOfWork.SaveChanges();
                }
                else
                {
                    TempData["error"] = "bản ghi không tồn tại";
                    return Json("bản ghi không tồn tại", JsonRequestBehavior.AllowGet);
                }

                TempData["message"] = "Cập nhật thành công!";
                return Json("OK", JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                TempData["error"] = "Lỗi Cập nhật: " + ex.Message;
                return Json("Lỗi Cập nhật", JsonRequestBehavior.AllowGet);
            }
        }
        public async Task<JsonResult> Delete(long id)
        {
            try
            {
                Round item = new Round();
                item = _unitOfWork.GetRepositoryInstance<Round>().GetFirstOrDefaultByParameter(o => o.ID == id);
                if (item != null)
                {
                    _unitOfWork.GetRepositoryInstance<Round>().Remove(item);
                    _unitOfWork.SaveChanges();
                }
                else
                {
                    TempData["error"] = "bản ghi không tồn tại";
                    return Json("bản ghi không tồn tại", JsonRequestBehavior.AllowGet);
                }

                TempData["message"] = "Xóa thành công!";
                return Json("OK", JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                TempData["error"] = "Lỗi xóa: " + ex.Message;
                return Json("Lỗi xóa", JsonRequestBehavior.AllowGet);
            }
        }
    }
}

Chess.CMS/Areas/Admin/Views/Round/Index.cshtml
@model IEnumerable<Chess.Model.Round>
@{
    ViewBag.Title = "Quản lý vòng đấu";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Danh sách vòng đấu</h2>
                <div class="pull-right">
                    <button type="button" onclick="openadd()" class="btn btn-success">Thêm mới</button>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <div id="datatable_wrapper" class="dataTables_wrapper form-inline dt-bootstrap no-footer">
                    <table id="datatable" class="table table-striped table-bordered dataTable no-footer" role="grid" aria-describedby="datatable_info">
                        <thead>
                            <tr role="row">
                                <th style="text-align:center">Mã vòng đấu</th>
                                <th style="text-align:center">Tên vòng đấu</th>
                                <th style="text-align:center">Ghi chú</th>
                                <th style="width:15%!important;text-align:center">Tác vụ</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model != null)
                            {
                                foreach (var item in Model)
                                {
                            <tr>
                                <td>@item.ID</td>
                                <td>@item.name</td>
                                <td>@item.note</td>
                                <td style="width:15%; text-align:center">
                                    <button type="button" onclick="openedit(@item.ID, '@item.name', '@item.note')" class="btn btn-primary">Sửa</button>
                                    <button type="button" onclick="confirmremove(@item.ID)" class="btn btn-danger">Xóa</button>
                                </td>
                            </tr>
                                }
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="divProcessing" style="position:fixed;top:0px; left:0px; height:3000px;width :100%;text-align:center;
         background:#f5f5f5;
         opacity:0.5;
                                z-index:999;
                                position:absolute;
                                left:0px;
                                top :0px;
                                cursor: wait; display:none">
    <img style="position: absolute;top: 50%;" src="~/Images/processing.gif" alt="" width="70" height="70" />

</div>


<div class="modal fade modeladd" id="modeladd" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Thêm mới</h4>
            </div>
            <div class="modal-body">
                <div class="x_content">
                    <br />
                    <form id="demo-form2" data-parsley-validate class="form-horizontal form-label-left">
                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="tencaphoc">
                                Tên vòng đấu <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input type="text" id="name" name="name" required="required" class="form-control col-md-7 col-xs-12">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="macaphoc">
                                Ghi chú <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input type="text" id="note" name="note" required="required" class="form-control col-md-7 col-xs-12">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="modal-footer" style="text-align:center">
                <button type="button" class="btn btn-primar" data-dismiss="modal">Hủy</button>
                <button type="button" id="btnThem" class="btn btn-success" data-dismiss="modal">Thêm</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade modeledit" id="modeledit" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Cập nhật</h4>
            </div>
            <div class="modal-body">
                <div class="x_content">
                    <br />
                    <form id="demo-form2" data-parsley-validate class="form-horizontal form-label-left">
                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="macaphoc">
                                Tên vòng đấu <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input type="hidden" name="IdEdit" id="IdEdit" value="" />
                                <input type="text" id="name_edit" name="name_eidt" required="required" class="form-control col-md-7 col-xs-12">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="tencaphoc">
                               Ghi chú <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input type="text" id="note_edit" name="note_edit" required="required" class="form-control col-md-7 col-xs-12">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="modal-footer" style="text-align:center">
                <button type="button" class="btn btn-primar" data-dismiss="modal">Hủy</button>
                <button type="button" id="btnSua" class="btn btn-success" data-dismiss="modal">Cập nhật</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade modeldelete" id="modeldelete" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Confirm</h4>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <center>
                        <input type="hidden" name="IdXoa" id="IdXoa" value="" />
                        <h3>Bạn có chăc muốn xóa?</h3>
                    </center>
                </div>
            </div>
            <div class="modal-footer" style="text-align:center">
                <button type="button" class="btn btn-primar" data-dismiss="modal">Hủy</button>
                <button type="button" id="btnXoa" class="btn btn-success" data-dismiss="modal">Xóa</button>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $('#datatable').DataTable();
    });

    function openadd() {
        $('#modeladd').modal({ backdrop: 'static', keyboard: false })
    }
    function openedit(id, name, note) {
        $('#IdEdit').val(id);
        $('#name_edit').val(name);
        $('#note_edit').val(note);
        $('#modeledit').modal({ backdrop: 'static', keyboard: false })
    }
    function confirmremove(id) {
        $('#IdXoa').val(id);
        $('#modeldelete').modal({ backdrop: 'static', keyboard: false })
    }

    $('#btnThem').click(function () {
        var name = $('#name').val();
        var note = $('#note').val();

        if (name == "") {
            toastr.error('tên không được để trống');
            return false;
        }
        //if (tencaphoc == "") {
        //    toastr.error('tên cấp học không được để trống');
        //    return false;
        //}

        $("#divProcessing").show();
        $.ajax({
            type: "GET",
            url: '@Url.Action("AddRound", "Round")',
            data: { name: name, note: note},
            dataType: "json",
            contentType: 'application/json',
            success: function (data) {
                $("#divProcessing").hide();
                if (data == 'OK') {
                    setTimeout(function () { location.reload(); }, 2000);
                } else {
                    toastr.error(data);
                }
            },
            error: function (req, status, error) {
                $("#divProcessing").hide();
            }
        });
    })

    $('#btnSua').click(function () {
        var id = $('#IdEdit').val();
        var name = $('#name_edit').val();
        var note = $('#note_edit').val();
        if (name == "") {
            toastr.error('tên không được để trống');
            return false;
        }
        //if (tencaphoc == "") {
        //    toastr.error('tên cấp học không được để trống');
        //    return false;
        //}

        $("#divProcessing").show();
        $.ajax({
            type: "GET",
            url: '@Url.Action("EditRound", "Round")',
            data: { id: id, name: name, note: note},
            dataType: "json",
            contentType: 'application/json',
            success: function (data) {
                $("#divProcessing").hide();
                if (data == 'OK') {
                    setTimeout(function () { location.reload(); }, 2000);
                } else {
                    toastr.error(data);
                }
            },
            error: function (req, status, error) {
                $("#divProcessing").hide();
            }
        });
    })

    $('#btnXoa').click(function () {
        var id = $('#IdXoa').val();
        $("#divProcessing").show();
        $.ajax({
            type: "GET",
            url: '@Url.Action("Delete", "Round")',
            data: { id: id },
            dataType: "json",
            contentType: 'application/json',
            success: function (data) {
                $("#divProcessing").hide();
                if (data == 'OK') {
                    setTimeout(function () { location.reload(); }, 2000);
                } else {
                    toastr.error(data);
                }
            },
            error: function (req, status, error) {
                $("#divProcessing").hide();
            }
        });
    })
</script>