Chess.CMS/Areas/Admin/Controllers/MatchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Chess.CMS.Areas.Admin.Controllers
{
    public class MatchController : Controller
    {
        // GET: Admin/Match
        public ActionResult Index()
        {
            return View();
        }
    }
}

Chess.CMS/Areas/Admin/Views/Match/Index.cshtml
@{
    /**/

    ViewBag.Title = "Quản lý trận đấu";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<div>
    <div class="FilterMarket ">
        <div class="col-md-2">
            <select type="select" class="selectMarket form-control" data-placeholder="Tất cả" id="listRound"></select>
            <i></i>
        </div>
    </div>
    <div class="col-md-2">
        <button class="btn btn-block" style="background-color:#03a9f4;color:white" id="btnsearch">Tìm kiếm</button>
    </div>
</div>
<div class="col-md-12" id="divResult">

</div>
<script type="text/javascript">
        $(document).ready(function () {
            LoadListRound();
        });
        function LoadListRound() {
            $.ajax({
                type: "GET",
                url: "/RankAfterRound/LoadListRound",
                dataType: "json",
                contentType: 'application/json',
                success: function (result) {
                    $('#listRound').html(' <option value="-1">Vòng đấu</option>' + result);
                },
                error: function (req, status, error) {
                }
            });
        };
        $('#btnsearch').click(function () {
            var roundID = $('#listRound').children("option:selected").val();
            if (roundID == -1) {
                toastr.error('Hãy chọn vòng đấu');
                return false;
            }
            else if (roundID < 1 || roundID > 11) {
                toastr.error('Vòng đấu không tồn tại');
                return false;
            }
            var model = $('#divResult');
            $.ajax({
            url: "@Url.Action("GetMatch", "Match")",
                type: "GET",
                data: { roundID: roundID },
            dataType: 'html',
                success: function (result) {
                    if (result != null || result != 0) {
                        model.empty();
                        model.html(result);
                    }
                    else {
                        toastr.error('Vòng đấu chưa tồn tại');
                    }
            },
            error: function (error) {
                toastr.error('Vòng đấu chưa tồn tại');
            }
        });
        });
</script>

Chess.CMS/Areas/Admin/Views/Match/Match.cshtml
@model IEnumerable<Chess.CMS.Areas.Admin.Models.RankAfterRoundViewModel>

<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Bảng xếp hạng</h2>
                <div class="clearfix"></div>
            </div>
            @if (Model != null)
            {
                <div class="x_content">
                    <div id="datatable_wrapper" class="dataTables_wrapper form-inline dt-bootstrap no-footer">
                        <table id="datatable" class="table table-striped table-bordered dataTable no-footer" role="grid" aria-describedby="datatable_info" data-page-length='25' data-order='[[6, "des" ]]'>
                            <thead>
                                <tr role="row">
                                    <th style="text-align:center">ID</th>
                                    <th style="text-align:center">Tên</th>
                                    <th style="text-align:center">Năm sinh</th>
                                    <th style="text-align:center">Quốc tịch</th>
                                    <th style="text-align:center">Tổng điểm</th>
                                    <th style="text-align:center">Tổng điểm đối thủ đã gặp</th>
                                    <th style="text-align:center">Elo tức thời</th>
                                </tr>
                            </thead>
                            <tbody>

                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@item.player.ID</td>
                                        <td>@item.player.name</td>
                                        <td>@item.player.birthday</td>
                                        <td>@item.player.country</td>
                                        <td>@item.score</td>
                                        <td>@item.changeScore</td>
                                        <td>@item.elo</td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            }
            else <div><a>Chưa có bảng xếp hạng cho vòng đấu</a></div>

        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        $('#datatable').DataTable({
        });
    });
</script>